### PR TITLE
Append histo

### LINKED ISSUE #400: history left in broken state
https://github.com/nushell/nushell/issues/1977

The library always overwrites the history which does not have practical value. Instead it must only append new lines to the existing file.

### PR DESCRIPTION
**Pull request by gwenn**
Breaking change: a mutable reference is now needed to save history
Should fix #400

### CODE REVIEW

File: src/history.rs [hunk 1]
```diff
@@ -158,6 +153,40 @@ impl History {
...
+        file.lock_exclusive()?;
+        // we may need to truncate file before appending new entries
+        let mut other = Self {
+            entries: VecDeque::new(),
+            max_len: self.max_len,
+            ignore_space: self.ignore_space,
+            ignore_dups: self.ignore_dups,
+            new_entries: 0,
+        };
+        other.load(path)?;
```
Comment (gwenn) [inline src/history.rs:182]: I am not sure we can open `path` in `load` after `file.lock_exclusive`.

File: src/history.rs [hunk 2]
```diff
@@ -158,6 +153,40 @@ impl History {
...
+        let first_new_entry = self.entries.len() - self.new_entries;
+        for entry in self.entries.iter().skip(first_new_entry) {
+            other.add(entry);
+        }
+        other.save(path)?;
```
Comment (gwenn) [inline src/history.rs:187]: I am not sure we can open `path` in `save` after `file.lock_exclusive()`.

File: src/history.rs (hunk 1 above)
Comment (gwenn) [reply src/history.rs:182]: Ok, it works only on unix (or at least linux) but not on windows (see error in CI)...

File: src/history.rs [hunk 3]
```diff
@@ -158,6 +172,48 @@ impl History {
...
+        use fs2::FileExt;
+        use std::io::Seek;
+
+        if self.is_empty() || self.new_entries == 0 {
+            return Ok(());
+        }
+        let path = path.as_ref();
+        if !path.exists() || self.new_entries == self.max_len {
+            return self.save(path);
+        } else if self.can_just_append(path)? {
```
Comment (gwenn) [inline src/history.rs:191]: Maybe we should lock file before calling `can_just_append` ?
